deleted copyrighted code
BeyondRGB/Imaging-Art-beyond-RGB pull request #105
Opened 2022-10-27 20:40 UTC by jpakey99

2022-10-28 12:38 UTC, keenanm500 commented on frontend/src/renderer/util/openseadragon-curtian-sync.js
> +//     var self = this;
I don't think commenting it out will do it lol

2022-10-31 15:04 UTC, egc2846 requested changes
Properly delete please

2022-11-01 19:21 UTC, sk4900 approved these changes

2022-11-01 19:40 UTC, Victoriam7 approved these changes

2022-11-01 20:14 UTC, keenanm500 approved these changes
This is so far the best refactor of brgb done to date, well done. I look forward to removing more lines

2022-11-03 21:02 UTC, egc2846 approved these changes

2022-11-03 21:02 UTC, merged