io complete
BeyondRGB/Imaging-Art-beyond-RGB pull request #108
Opened 2022-11-01 17:24 UTC by Victoriam7

I/O functionality complete for now

2022-11-01 19:38 UTC, jpakey99 submitted a review, later dismissed

2022-11-01 21:44 UTC, egc2846 requested changes

2022-11-01 21:44 UTC, egc2846 commented on backend/src/pipelines.py
> +    This code is licensed under the MIT license (see LINSE.txt for details)
typo

2022-11-02 19:59 UTC, sk4900 commented on backend/src/pipelines.py
> +llection of all pipelines
typo

2022-11-02 20:00 UTC, sk4900 approved these changes

2022-11-03 21:13 UTC, egc2846 approved these changes

2022-11-03 21:16 UTC, Victoriam7 commented on backend/src/pipelines.py
> +    This code is licensed under the MIT license (see LINSE.txt for details)
Fixed

2022-11-03 21:16 UTC, Victoriam7 commented on backend/src/pipelines.py
> +llection of all pipelines
fixed

2022-11-03 21:17 UTC, sk4900 approved these changes

2022-11-03 21:17 UTC, keenanm500 approved these changes

2022-11-03 21:17 UTC, merged