spectral picker chart finished
BeyondRGB/Imaging-Art-beyond-RGB pull request #113
Opened 2022-11-22 00:04 UTC by jpakey99

2022-11-22 19:23 UTC, egc2846 submitted a review, later dismissed

2022-11-22 19:27 UTC, sk4900 approved these changes

2022-11-22 21:00 UTC, keenanm500 commented
I tested this, and I have to say the new color spectrum looks 🔥 

I do think there has to be a way to decide when we want to add a new line to the graph or completely replace the graph like it does today. There should at least be a way to remove lines from the graph. Let me know if you want to chat about this

2022-11-22 21:02 UTC, keenanm500 requested changes

2022-11-22 21:02 UTC, keenanm500 commented on frontend/src/renderer/components/Charts/LineChart.svelte
> +      let dataDict = [];
this could be `const`

2022-11-22 21:05 UTC, keenanm500 commented on frontend/src/renderer/components/Charts/LineChart.svelte
> +                  download: true,
I had difficulties with this also, we could check with them about how important it is. We can definitely figure this out though if necessary

2022-11-23 21:00 UTC, Victoriam7 submitted a review, later dismissed

2022-11-28 16:50 UTC, sk4900 commented on frontend/src/renderer/components/Charts/LineChart.svelte
> +              color:  '#fff'
I agree, I think we should use the full 6 characters in every case. Caps preferred

2022-11-28 16:51 UTC, sk4900 submitted a review, later dismissed

2022-11-29 15:17 UTC, jpakey99 commented on frontend/src/renderer/components/Charts/LineChart.svelte
> +  let seriesData = [];
nope.  I forgot to delete them from when I was trying something else.  Will make sure I delete

2022-11-29 15:18 UTC, jpakey99 commented on frontend/src/renderer/components/Charts/LineChart.svelte
> +              color:  '#fff'
sounds good.  I will make the change

2022-11-29 15:19 UTC, jpakey99 commented on frontend/src/renderer/components/Charts/LineChart.svelte
> -
I am pretty sure everything I deleted did not work with apex and was specific for the old chart

2022-11-29 16:48 UTC, egc2846 approved these changes

2022-11-29 19:48 UTC, keenanm500 commented on frontend/src/renderer/components/Charts/LineChart.svelte
> +                  download: true,
I'm sure there's a way to fix this. Might be worth pair-programming to find a fix. If there isn't a way to fix it normally, we could probably hack it by using an icon without text or something

2022-11-29 21:00 UTC, keenanm500 commented on frontend/src/renderer/components/Charts/LineChart.svelte
> +                  download: true,
@jpakey99 Got this fixed, nice work

2022-11-29 21:01 UTC, keenanm500 approved these changes

2022-11-30 18:47 UTC, sk4900 approved these changes

2022-12-01 14:58 UTC, merged