registration
BeyondRGB/Imaging-Art-beyond-RGB pull request #129
Opened 2023-02-04 19:05 UTC by egc2846

2023-02-04 19:44 UTC, Victoriam7 commented on backend/src/preprocessing.py
> +    reference_color = subject[0]
I think these are making copies. It would be better to just call subject[n] when you need one. For clarity you could make a constant in place of "n"

2023-02-04 19:46 UTC, Victoriam7 commented on backend/src/preprocessing.py
> +    img2_gray_norm = normalize(img2_gray, None, 0, 255, NORM_MINMAX).astype('uint8')
For memory saving please keep it in the same array or delete the img(n)_grey arrays after

2023-02-04 19:51 UTC, Victoriam7 requested changes
Do you have an example of this working on the actual images as opposed to the example book image? Please also a brief comment above some of the blocks of code explaining what they are doing

2023-02-04 19:59 UTC, egc2846 commented
> Do you have an example of this working on the actual images as opposed to the example book image? Please also a brief comment above some of the blocks of code in registration explaining what they are doing

I can show you what I have for image outputs in GIMP sometime today

2023-02-04 20:01 UTC, Victoriam7 commented on backend/src/preprocessing.py
> +    REFERENCE = 0
It might be better to pull this into constants.py to be consistent, but that's not a big deal for now. Final cleanup can come later

2023-02-07 17:45 UTC, Victoriam7 commented
While we are switching to other tasks so as to make progress, this task is not complete and thus should not be merged. It could still be a WIP

2023-02-07 17:45 UTC, closed without merging