Backend refactor arg handling
BeyondRGB/Imaging-Art-beyond-RGB pull request #137
Opened 2023-02-14 21:55 UTC by keenanm500

This modifies how we accept input into the backend-refactor. Args should be in the same order that they are currently inputted, with the addition of a (currently unused) color target option (NGT, etc). This also displays help info if someone doesn't input data correctly.

2023-02-14 21:56 UTC, keenanm500 commented on backend/src/main.py
> +    parser.add_argument('bottom_right_y', help='Pixel value of the bottom-right of the color target from the top end of the color-target image')
Brendan please verify these descriptions

(I realize now you're gonna be mad at the length of these lines)

2023-02-14 22:08 UTC, jpakey99 approved these changes

2023-02-14 23:08 UTC, Victoriam7 requested changes
The usage statement is hard to read. It may be better to override the usage statment since argpars's default is pretty bad. I we go this way, it can be done by adding a -h, --help options with the action

```py
 class HelpAction(argparse._HelpAction):
     """ Print usage statement when -h or --help is passed """
     def __call__(self, parser, namespace, values, option_string=None):
         print(USAGE_STATEMENT)
         parser.exit()
```

2023-02-14 23:08 UTC, Victoriam7 commented on backend/src/main.py
> +    """
For consistency it would be better to make these # comments unless they are large multiline comments

2023-02-14 23:08 UTC, Victoriam7 commented on backend/src/main.py
> +    """
not a huge deal though

2023-02-14 23:08 UTC, Victoriam7 commented on backend/src/main.py
> +    images_help = '''
Move this to constants for the help messages if we stick with those

2023-02-14 23:08 UTC, Victoriam7 commented on backend/src/main.py
>      """ Setup packet """
Packet setup should be extracted to a function so we can base it off of the requested pipeline

2023-02-14 23:13 UTC, Victoriam7 commented
```py
 15 class Parser(argparse.ArgumentParser):
 16     """ Custom parser to allow for a custom error message """
 17
 18     def error(self, message):
 19         print(USAGE_STATEMENT)
 20         print('\033[91m' + 'error: %s\033[00m' % message)
 21         sys.exit(2)

```

2023-02-15 16:11 UTC, jpakey99 submitted a review, later dismissed

2023-02-16 20:05 UTC, Victoriam7 approved these changes
This looks really good

2023-02-16 20:05 UTC, Victoriam7 commented on backend/src/parser.py
> +import sys
Please add a file level comment to the top of the new file similar to the other files

2023-02-16 20:52 UTC, sk4900 submitted a review, later dismissed

2023-02-19 22:02 UTC, Victoriam7 approved these changes
This looks great!

2023-02-21 13:34 UTC, jpakey99 approved these changes

2023-02-21 19:46 UTC, egc2846 approved these changes

2023-02-21 21:17 UTC, merged