Create requirements.txt
BeyondRGB/Imaging-Art-beyond-RGB pull request #159
Opened 2023-03-23 19:57 UTC by egc2846

2023-03-23 20:09 UTC, jpakey99 approved these changes

2023-03-25 22:09 UTC, Victoriam7 requested changes

2023-03-25 22:09 UTC, Victoriam7 commented on backend/Makefile
>  OUT_DIR = dist/
This comment is to hold merging until dependent pr is merged. That PR will also have a merge conflict once dependent PR is merged. Once OS changes are in feel free to close this comment

2023-03-25 22:09 UTC, Victoriam7 commented on requirements.txt
> +dataclasses
dataclasses is built in

2023-03-26 00:43 UTC, Victoriam7 requested changes

2023-03-26 00:43 UTC, Victoriam7 commented on requirements.txt
> +opencv-python==4.6.0.66
Could you also add easygui==0.98.3

2023-03-26 00:43 UTC, Victoriam7 commented on backend/Makefile
>  DATA_DIR = data
This file should be at the same level as the Makefile. backend/requirements.txt

2023-03-30 19:26 UTC, Victoriam7 requested changes

2023-03-30 19:26 UTC, Victoriam7 commented on backend/Makefile
> +	find -iname "*.pyc" -delete
why are we deleting .pyc files?

2023-03-30 19:26 UTC, Victoriam7 commented on backend/Makefile
> +	 	. venv/bin/activate; \
This command fails when run in the make file. It works when run manually for some reason though.

2023-04-01 23:55 UTC, merged